# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a442065cf8552ef6045ca97f9d5a00172d5aa1c1532b4ccfbcfa49567ac2f240cbfa4696f17738fbcc5ddb7f4903e8c78ab2206c36e5f19f9695f3d2a1a013b4

test:
  secret_key_base: 6e9bd01dedcc96defce5747a239372267a0ac25fb253f9d6b6c0e8a1edac33d45d33f2d664033c5e0055fbb39e54d999a4f486b49a333587c7fcf183197273b4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
